### ISSUE TITLE
Server crashes if losing connection to rptools.net

### ISSUE THREAD

**Issue by Antafes** [cniemira/maptool-StandaloneServer#6]
If the server gets an http status code over 400, it crashes and you lose all the unsaved changes.
I'll add the complete error message if it occurs the next time, because yet I lost it...

**Comment by Antafes** [comment]
Ping

**Comment by Antafes** [comment]
And here the error messages:

> Exception in thread "main" com.thoughtworks.xstream.io.StreamException:  : Stream closed
>         at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:126)
>         at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
>         at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141)
>         at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118)
>         at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103)
>         at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:63)
>         at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:58)
>         at com.thoughtworks.xstream.XStream.fromXML(XStream.java:895)
>         at net.rptools.lib.io.PackedFile.getFileObject(PackedFile.java:552)
>         at net.rptools.maptool.server.StandaloneServer.loadAssets(StandaloneServer.java:64)
>         at net.rptools.maptool.server.StandaloneServer.loadCampaignFile(StandaloneServer.java:102)
>         at net.rptools.maptool.server.StandaloneServer.main(StandaloneServer.java:227)
> Caused by: java.io.IOException: Stream closed
>         at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:151)
>         at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
>         at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
>         at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
>         at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
>         at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
>         at java.io.InputStreamReader.read(InputStreamReader.java:184)
>         at java.io.BufferedReader.read1(BufferedReader.java:203)
>         at java.io.BufferedReader.read(BufferedReader.java:279)
>         at java.io.LineNumberReader.read(LineNumberReader.java:164)
>         at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:2992)
>         at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
>         at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410)
>         at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
>         at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
>         at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
>         ... 11 more
> Exception in thread "Thread-7" com.caucho.hessian.client.HessianRuntimeException: java.net.ConnectException: Die Wartezeit für die Verbindung ist abgelaufen
>         at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:295)
>         at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:161)
>         at com.sun.proxy.$Proxy0.heartBeat(Unknown Source)
>         at net.rptools.maptool.client.MapToolRegistry.heartBeat(MapToolRegistry.java:65)
>         at net.rptools.maptool.server.MapToolServer$HeartbeatThread.run(MapToolServer.java:192)
> Caused by: java.net.ConnectException: Die Wartezeit für die Verbindung ist abgelaufen
>         at java.net.PlainSocketImpl.socketConnect(Native Method)
>         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
>         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:579)
>         at java.net.Socket.connect(Socket.java:528)
>         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
>         at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:308)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:326)
>         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:997)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
>         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851)
>         at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1092)
>         at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:293)
>         ... 4 more

**Comment by cniemira** [comment]
Interesting... I should have time to look into this next week. Shouldn't be too hard to replicate.

**Comment by Antafes** [comment]
Would be very nice, if you could fix this. I would have tried it myself, but I don't have the time to do it :(

**Comment by Antafes** [comment]
Hi,
did you have time to look into this?
It's really annoying to find the server is crashed from time to time...

**Comment by cniemira** [comment]
I just pushed a small patch that should fix this issue. I'd like to test, and possibly do something about the autosave request in issue#4 before I drop another release.

**Comment by Antafes** [comment]
I will have a look at the patch. Thanks in advance.

**Comment by Antafes** [comment]
The above mentioned problem seems to be solved. But the server sometimes looses the connection and exits...
Mostly this happens if rptools is loosing the database connection.
